In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv('/content/drive/MyDrive/EG/translated_dataset/mbart50/mbart50_p6.csv')

In [48]:
df = df.reset_index(drop=False)

Add a column with proper indicing if not present

In [49]:
df

,index,Unnamed: 0,essay_id,essay_set,essay,score,essay_hindi,mbart50_m2m
0,0,8886,14834,6,There were many obstacles that the builders fa...,2,एम्पायर स्टेट बिल्डिंग में डिरिगिबल्स डॉक करने...,इम्पर स्टेट भवनमा dirigibles डक गर्ने प्रयास ग...
1,1,8887,14835,6,"Him from the start, there would have been many...",3,"उसे शुरू से ही, हवा में कुछ @ NUM1 फीट डॉक करन...","उहाँलाई सुरुदेखि नै, केही @NUM1 फीट आकाशमा डक ..."
2,2,8888,14836,6,The builders of the Empire State Building face...,4,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां डॉक...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...
3,3,8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1,मार्ग में मूरिंग मस्त मार्सिया एमिडॉन @ CAPS1 ...,मार्गमा मार्सिया अमीडन @CAPS1 द्वारा निर्माण ग...
4,4,8890,14838,6,The builders of the Empire State Building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को डिरिगिबल...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...
...,...,...,...,...,...,...,...,...
1795,1795,10681,16629,6,The one obstacle the builders had when trying ...,0,इस इमारत को बनाने की कोशिश करते समय बिल्डरों क...,निर्माणकर्ताहरूले यो भवन निर्माण गर्ने प्रयास ...
1796,1796,10682,16630,6,Some of the problems with the constructing of ...,2,डॉकिंग डिरिगिबल्स के निर्माण के साथ कुछ समस्या...,डकिङ डाइरिभेलको निर्माणमा केही समस्याहरू निम्न...
1797,1797,10683,16631,6,The builders of the Empire State building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां कुछ...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...
1798,1798,10684,16632,6,The obstacles the builders of the Empire State...,2,एम्पायर स्टेट बिल्डिंग के बिल्डरों की बाधाएं य...,इम्पर स्टेट भवनका निर्माणकर्ताहरूका अवरोधहरू य...
1799,1799,10685,16633,6,You want me to tell you what they had to go th...,2,आप चाहते हैं कि मैं आपको बता दूं कि डिरिगिबल्स...,तपाईँले मलाई बताउन चाहनुहुन्छ तिनीहरूलाई त्यहा...

In [50]:
def addCol(x):
  return x

Preprocessing

In [51]:
import re
def remove_mentions(x):
  if x=='nan':
    return ""
  x = re.sub("@[a-zA-Z0-9 ]+", " ", x)
  return x

In [52]:
df.mbart50_m2m = df.mbart50_m2m.apply( lambda x: remove_mentions(str(x)))

In [53]:
df.head()

,index,Unnamed: 0,essay_id,essay_set,essay,score,essay_hindi,mbart50_m2m
0,0,8886,14834,6,There were many obstacles that the builders fa...,2,एम्पायर स्टेट बिल्डिंग में डिरिगिबल्स डॉक करने...,इम्पर स्टेट भवनमा dirigibles डक गर्ने प्रयास ग...
1,1,8887,14835,6,"Him from the start, there would have been many...",3,"उसे शुरू से ही, हवा में कुछ @ NUM1 फीट डॉक करन...","उहाँलाई सुरुदेखि नै, केही फीट आकाशमा डक गर्न ..."
2,2,8888,14836,6,The builders of the Empire State Building face...,4,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां डॉक...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...
3,3,8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1,मार्ग में मूरिंग मस्त मार्सिया एमिडॉन @ CAPS1 ...,मार्गमा मार्सिया अमीडन द्वारा निर्माण गरिएको ...
4,4,8890,14838,6,The builders of the Empire State Building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को डिरिगिबल...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...

In [54]:
#stopwords removal
stop_words = []
with open('/content/drive/MyDrive/EG/nepali_stopwords.txt') as f:
    for line in f:
        stop_words.append(line.strip())

In [55]:
def vocab_size(x):
  #removing punctuation
  x = remove_mentions(x)

  x = x.replace("।", " ")
  x = x.replace("!", " ")
  x = x.replace("@", " ")
  x = x.replace(",", " ")
  x = x.replace("?", " ")

  #extracting words
  vocab = x.split()

  final_vocab = []

  for word in vocab:
    if word != " " and word not in stop_words:
        final_vocab.append(word)

  dict = {}

  for word in final_vocab:
    if word not in dict:
      dict.update({ word : 1 })
    else:
      dict[word] += 1

  cnt = 0

  for key, value in dict.items():
      cnt = cnt + 1

  return cnt

In [56]:
df['vocab_size'] = df.mbart50_m2m.apply( lambda x: vocab_size(x))

In [57]:
def rare_words(x):
  #removing punctuation
  x = x.replace("।", " ")
  x = x.replace("!", " ")
  x = x.replace("@", " ")
  x = x.replace(",", " ")
  x = x.replace("?", " ")

  #extracting words
  vocab = x.split()

  final_vocab = []

  for word in vocab:
    if word != " " and word not in stop_words:
        final_vocab.append(word)

  dict = {}

  for word in final_vocab:
    if word not in dict:
      dict.update({ word : 1 })
    else:
      dict[word] += 1

  cnt = 0
  for key, value in dict.items():
    if value == 1:
      cnt = cnt + 1

  return cnt

In [58]:
df['unique_words_count'] = df.mbart50_m2m.apply( lambda x: rare_words(x))

In [59]:
df.head()

,index,Unnamed: 0,essay_id,essay_set,essay,score,essay_hindi,mbart50_m2m,vocab_size,unique_words_count
0,0,8886,14834,6,There were many obstacles that the builders fa...,2,एम्पायर स्टेट बिल्डिंग में डिरिगिबल्स डॉक करने...,इम्पर स्टेट भवनमा dirigibles डक गर्ने प्रयास ग...,57,50
1,1,8887,14835,6,"Him from the start, there would have been many...",3,"उसे शुरू से ही, हवा में कुछ @ NUM1 फीट डॉक करन...","उहाँलाई सुरुदेखि नै, केही फीट आकाशमा डक गर्न ...",78,69
2,2,8888,14836,6,The builders of the Empire State Building face...,4,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां डॉक...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,73,62
3,3,8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1,मार्ग में मूरिंग मस्त मार्सिया एमिडॉन @ CAPS1 ...,मार्गमा मार्सिया अमीडन द्वारा निर्माण गरिएको ...,101,90
4,4,8890,14838,6,The builders of the Empire State Building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को डिरिगिबल...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,72,60

**Semantic Overlap**

In [60]:
!pip install tensorflow_text

Requirement already satisfied: tensorflow_text in /usr/local/lib/python3.10/dist-packages (2.15.0)
Requirement already satisfied: tensorflow-hub>=0.13.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow_text) (0.16.1)
Requirement already satisfied: tensorflow<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow_text) (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (16.0.6)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (1.25.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (4.10.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (1.62.0)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.16,>=2.15.0->tensorflow_text) (2.15.0)
Requirement already satisfied: tf-keras>=2.14.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow-hub>=0.13.0->tensorflow_text) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow<2.16,>=2.15.0->tensorflow_text) (0.42.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (3.5.2)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (3.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (2.1.5)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow<2.16,>=2.15.0->tensorflow_text) (3.2.2)

In [61]:
!pip install bert-for-tf2

Requirement already satisfied: bert-for-tf2 in /usr/local/lib/python3.10/dist-packages (0.14.9)
Requirement already satisfied: py-params>=0.9.6 in /usr/local/lib/python3.10/dist-packages (from bert-for-tf2) (0.10.2)
Requirement already satisfied: params-flow>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from bert-for-tf2) (0.8.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from params-flow>=0.8.0->bert-for-tf2) (1.25.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from params-flow>=0.8.0->bert-for-tf2) (4.66.2)

In [62]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub
import tensorflow_text as text
from bert import bert_tokenization
import numpy as np
from scipy.spatial import distance

def get_model(model_url, max_seq_length):
  inputs = dict(
    input_word_ids=tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32),
    input_mask=tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32),
    input_type_ids=tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32),
    )
  muril_layer = hub.KerasLayer(model_url, trainable=True)
  outputs = muril_layer(inputs)
  assert 'sequence_output' in outputs
  assert 'pooled_output' in outputs
  assert 'encoder_outputs' in outputs
  assert 'default' in outputs
  return tf.keras.Model(inputs=inputs,outputs=outputs["pooled_output"]), muril_layer
#function call
max_seq_length = 128
muril_model, muril_layer = get_model(
    model_url="https://tfhub.dev/google/MuRIL/1", max_seq_length=max_seq_length)

vocab_file = muril_layer.resolved_object.vocab_file.asset_path.numpy()
do_lower_case = muril_layer.resolved_object.do_lower_case.numpy()
tokenizer = bert_tokenization.FullTokenizer(vocab_file, do_lower_case)

def create_input(input_strings, tokenizer, max_seq_length):
  input_ids_all, input_mask_all, input_type_ids_all = [], [], []
  for input_string in input_strings:
    input_tokens = ["[CLS]"] + tokenizer.tokenize(input_string) + ["[SEP]"]
    input_ids = tokenizer.convert_tokens_to_ids(input_tokens)
    sequence_length = min(len(input_ids), max_seq_length)
    if len(input_ids) >= max_seq_length:
      input_ids = input_ids[:max_seq_length]
    else:
      input_ids = input_ids + [0] * (max_seq_length - len(input_ids))
    input_mask = [1] * sequence_length + [0] * (max_seq_length - sequence_length)
    input_ids_all.append(input_ids)
    input_mask_all.append(input_mask)
    input_type_ids_all.append([0] * max_seq_length)
  return np.array(input_ids_all), np.array(input_mask_all), np.array(input_type_ids_all)

def encode(input_text):
  input_ids, input_mask, input_type_ids = create_input(input_text,tokenizer,max_seq_length)
  inputs = dict(
      input_word_ids=input_ids,
      input_mask=input_mask,
      input_type_ids=input_type_ids,
  )
  return muril_model(inputs)

In [63]:
def get_overlap(x):
  sentences = x.split("।")
  scores = []

  n = len(sentences)
  prev = 0
  curr = 4

  while curr < n:
    temp = []
    temp.append(sentences[prev])
    temp.append(sentences[curr])

    embeddings = encode(temp)

    scores.append(distance.cosine(np.array(embeddings[0]), np.array(embeddings[1])))

    prev = prev + 4
    curr = curr + 4

  curr = curr%n
  temp = []
  temp.append(sentences[prev])
  temp.append(sentences[curr])

  embeddings = encode(temp)

  scores.append(distance.cosine(np.array(embeddings[0]), np.array(embeddings[1])))


  #returning avg semantic overlap score
  return sum(scores)/len(scores)

In [64]:
df['overlap_score'] = df.mbart50_m2m.apply(lambda x: get_overlap(x))

In [65]:
df.head()

,index,Unnamed: 0,essay_id,essay_set,essay,score,essay_hindi,mbart50_m2m,vocab_size,unique_words_count,overlap_score
0,0,8886,14834,6,There were many obstacles that the builders fa...,2,एम्पायर स्टेट बिल्डिंग में डिरिगिबल्स डॉक करने...,इम्पर स्टेट भवनमा dirigibles डक गर्ने प्रयास ग...,57,50,0.001299
1,1,8887,14835,6,"Him from the start, there would have been many...",3,"उसे शुरू से ही, हवा में कुछ @ NUM1 फीट डॉक करन...","उहाँलाई सुरुदेखि नै, केही फीट आकाशमा डक गर्न ...",78,69,0.001432
2,2,8888,14836,6,The builders of the Empire State Building face...,4,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां डॉक...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,73,62,0.000842
3,3,8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1,मार्ग में मूरिंग मस्त मार्सिया एमिडॉन @ CAPS1 ...,मार्गमा मार्सिया अमीडन द्वारा निर्माण गरिएको ...,101,90,0.001175
4,4,8890,14838,6,The builders of the Empire State Building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को डिरिगिबल...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,72,60,0.001339

In [66]:
import re
re.findall("@[a-zA-Z0-9 ]+", df.mbart50_m2m[0])

[]

**Statistical Features** - Essay Length, Average Sentence Length, Average Word Length and Readability Score

In [67]:
# df['Unnamed: 0'] = np.arange(len(df))
# # to add indexing

In [68]:
df

,index,Unnamed: 0,essay_id,essay_set,essay,score,essay_hindi,mbart50_m2m,vocab_size,unique_words_count,overlap_score
0,0,8886,14834,6,There were many obstacles that the builders fa...,2,एम्पायर स्टेट बिल्डिंग में डिरिगिबल्स डॉक करने...,इम्पर स्टेट भवनमा dirigibles डक गर्ने प्रयास ग...,57,50,0.001299
1,1,8887,14835,6,"Him from the start, there would have been many...",3,"उसे शुरू से ही, हवा में कुछ @ NUM1 फीट डॉक करन...","उहाँलाई सुरुदेखि नै, केही फीट आकाशमा डक गर्न ...",78,69,0.001432
2,2,8888,14836,6,The builders of the Empire State Building face...,4,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां डॉक...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,73,62,0.000842
3,3,8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1,मार्ग में मूरिंग मस्त मार्सिया एमिडॉन @ CAPS1 ...,मार्गमा मार्सिया अमीडन द्वारा निर्माण गरिएको ...,101,90,0.001175
4,4,8890,14838,6,The builders of the Empire State Building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को डिरिगिबल...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,72,60,0.001339
...,...,...,...,...,...,...,...,...,...,...,...
1795,1795,10681,16629,6,The one obstacle the builders had when trying ...,0,इस इमारत को बनाने की कोशिश करते समय बिल्डरों क...,निर्माणकर्ताहरूले यो भवन निर्माण गर्ने प्रयास ...,54,45,0.000524
1796,1796,10682,16630,6,Some of the problems with the constructing of ...,2,डॉकिंग डिरिगिबल्स के निर्माण के साथ कुछ समस्या...,डकिङ डाइरिभेलको निर्माणमा केही समस्याहरू निम्न...,33,32,0.000000
1797,1797,10683,16631,6,The builders of the Empire State building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां कुछ...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,53,44,0.000000
1798,1798,10684,16632,6,The obstacles the builders of the Empire State...,2,एम्पायर स्टेट बिल्डिंग के बिल्डरों की बाधाएं य...,इम्पर स्टेट भवनका निर्माणकर्ताहरूका अवरोधहरू य...,30,24,0.000000
1799,1799,10685,16633,6,You want me to tell you what they had to go th...,2,आप चाहते हैं कि मैं आपको बता दूं कि डिरिगिबल्स...,तपाईँले मलाई बताउन चाहनुहुन्छ तिनीहरूलाई त्यहा...,67,58,0.001352

In [69]:
!unzip /content/drive/MyDrive/EG/model/indic_nlp_library-master.zip

Archive:  /content/drive/MyDrive/EG/model/indic_nlp_library-master.zip
05bb7c93b63d32729f576028b5ace0efc2396138
replace indic_nlp_library-master/LICENSE? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [70]:
!unzip /content/drive/MyDrive/EG/model/indic_nlp_resources.zip

Archive:  /content/drive/MyDrive/EG/model/indic_nlp_resources.zip
replace indic_nlp_resources/README.md? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [71]:
!pip install indic-nlp-library

Requirement already satisfied: indic-nlp-library in /usr/local/lib/python3.10/dist-packages (0.92)
Requirement already satisfied: sphinx-argparse in /usr/local/lib/python3.10/dist-packages (from indic-nlp-library) (0.4.0)
Requirement already satisfied: sphinx-rtd-theme in /usr/local/lib/python3.10/dist-packages (from indic-nlp-library) (2.0.0)
Requirement already satisfied: morfessor in /usr/local/lib/python3.10/dist-packages (from indic-nlp-library) (2.0.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from indic-nlp-library) (1.5.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from indic-nlp-library) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->indic-nlp-library) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->indic-nlp-library) (2023.4)
Requirement already satisfied: sphinx>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from sphinx-argparse->indic-nlp-library) (5.0.2)
Requirement already satisfied: docutils<0.21 in /usr/local/lib/python3.10/dist-packages (from sphinx-rtd-theme->indic-nlp-library) (0.18.1)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in /usr/local/lib/python3.10/dist-packages (from sphinx-rtd-theme->indic-nlp-library) (4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->indic-nlp-library) (1.16.0)
Requirement already satisfied: sphinxcontrib-applehelp in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (1.0.8)
Requirement already satisfied: sphinxcontrib-devhelp in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (1.0.6)
Requirement already satisfied: sphinxcontrib-jsmath in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (2.0.5)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (1.1.10)
Requirement already satisfied: sphinxcontrib-qthelp in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (1.0.7)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (3.1.3)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (2.16.1)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (2.2.0)
Requirement already satisfied: babel>=1.3 in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (2.14.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (0.7.16)
Requirement already satisfied: imagesize in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (1.4.1)
Requirement already satisfied: requests>=2.5.0 in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (2.31.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (23.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=2.3->sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.5.0->sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.5.0->sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.5.0->sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.5.0->sphinx>=1.2.0->sphinx-argparse->indic-nlp-library) (2024.2.2)

In [72]:
import sys
from indicnlp import common
from indicnlp import loader
# The path to the local git repo for Indic NLP library
INDIC_NLP_LIB_HOME=r"/content/indic_nlp_library-master"

# The path to the local git repo for Indic NLP Resources
INDIC_NLP_RESOURCES=r"/content/indic_nlp_resources"

sys.path.append(r'{}'.format(INDIC_NLP_LIB_HOME))

common.set_resources_path(INDIC_NLP_RESOURCES)
loader.load()

In [73]:
from indicnlp.syllable import  syllabifier
lang='ne'

In [74]:
# data = [['goo','प्रिय स्थानीय अखबार मलाई']]
# df = pd.DataFrame(data,columns=['xyz','google'])

In [75]:
# df

In [76]:
essays=df["mbart50_m2m"]
essays

0       इम्पर स्टेट भवनमा dirigibles डक गर्ने प्रयास ग...
1       उहाँलाई सुरुदेखि नै, केही  फीट आकाशमा डक गर्न ...
2       इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...
3       मार्गमा मार्सिया अमीडन  द्वारा निर्माण गरिएको ...
4       इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...
                              ...
1795    निर्माणकर्ताहरूले यो भवन निर्माण गर्ने प्रयास ...
1796    डकिङ डाइरिभेलको निर्माणमा केही समस्याहरू निम्न...
1797    इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...
1798    इम्पर स्टेट भवनका निर्माणकर्ताहरूका अवरोधहरू य...
1799    तपाईँले मलाई बताउन चाहनुहुन्छ तिनीहरूलाई त्यहा...
Name: mbart50_m2m, Length: 1800, dtype: object

In [77]:
l_of_features = []
readability_score = []

for i in range(len(essays)):
    no_of_words = 0
    no_of_sentences = 0
    total_len_of_words = 0
    no_poly_syllables = 0
    essay = essays[i]

    if essay == "":
        l_of_features.append([0, 0, 0])
        readability_score.append(0)
        continue

    # One essay
    essay = essay.replace("!", "।")
    essay = essay.replace("?", "।")
    temp = essay.split("।")

    # Number of sentences
    no_of_sentences = len(temp)

    for j in range(len(temp)):
        b = temp[j].replace(",", " ").split()
        no_of_words += len(b)

        for k in range(len(b)):
            total_len_of_words += len(b[k])

            # Assumed strictly greater than 2
            if len(' '.join(syllabifier.orthographic_syllabify_improved(b[k], lang))) > 2:
                no_poly_syllables += 1

    # Check for division by zero
    if no_of_sentences == 0 or no_of_words == 0:
        l_of_features.append([no_of_words, 0, 0])
    else:
        # Check for division by zero
        if no_of_words == 0:
            l_of_features.append([no_of_words, 0, 0])
        else:
            l_of_features.append([no_of_words, (no_of_words / no_of_sentences), (total_len_of_words / no_of_words)])

    temp5 = -2.34 + (2.14 * (total_len_of_words / (no_of_words + 1))) + (0.01 * no_poly_syllables)
    readability_score.append(temp5)

In [78]:
# l_of_features=[]
# #essay_length, avg_sentence_length, avg_word_length
# readability_score=[]
# for i in range(len(essays)):
#   no_of_words=0
#   no_of_sentences=0
#   total_len_of_words=0
#   no_poly_syllables=0
#   essay=essays[i]
#   if essay=="":
#     l_of_features.append([0,0,0])
#     readability_score.append(0)
#     continue
#   #one essay
#   essay = essay.replace("!","।")
#   essay = essay.replace("?","।")
#   temp=essay.split("।")
#   # print(temp)
#   #print(temp) number of sentences
#   no_of_sentences=len(temp)
#   for j in range(len(temp)):
#     b=temp[j].replace(","," ").split()
#     no_of_words+=len(b)
#     for k in range(len(b)):
#       total_len_of_words+=len(b[k])
#       #assumed strictly greater than 2
#       if(len(' '.join(syllabifier.orthographic_syllabify_improved(b[k],lang)).split()))>2:
#         no_poly_syllables+=1
#         # print(no_poly_syllables)
#   l_of_features.append([no_of_words,(no_of_words/no_of_sentences),(total_len_of_words/no_of_words)])
#   temp5=-2.34+(2.14*(total_len_of_words/no_of_words))+(0.01*no_poly_syllables)
#   readability_score.append(temp5)

In [79]:
l_of_features

[[92, 13.142857142857142, 5.934782608695652],
 [138, 13.8, 5.427536231884058],
 [117, 13.0, 5.769230769230769],
 [157, 15.7, 5.484076433121019],
 [128, 11.636363636363637, 5.65625],
 [129, 11.727272727272727, 5.666666666666667],
 [106, 15.142857142857142, 5.745283018867925],
 [103, 14.714285714285714, 5.533980582524272],
 [100, 10.0, 5.62],
 [103, 7.923076923076923, 5.533980582524272],
 [190, 11.875, 5.152631578947369],
 [235, 12.368421052631579, 5.940425531914894],
 [150, 13.636363636363637, 5.253333333333333],
 [155, 11.923076923076923, 5.548387096774194],
 [97, 16.166666666666668, 5.536082474226804],
 [125, 15.625, 5.6],
 [111, 13.875, 5.324324324324325],
 [96, 12.0, 5.510416666666667],
 [72, 18.0, 5.013888888888889],
 [59, 11.8, 5.084745762711864],
 [88, 8.8, 5.75],
 [181, 15.083333333333334, 5.033149171270718],
 [134, 10.307692307692308, 5.559701492537314],
 [178, 12.714285714285714, 5.230337078651686],
 [96, 16.0, 5.25],
 [128, 11.636363636363637, 5.3984375],
 [148, 14.8, 5.445945945945946],
 [161, 13.416666666666666, 5.751552795031056],
 [116, 12.88888888888889, 6.086206896551724],
 [86, 14.333333333333334, 5.1395348837209305],
 [125, 17.857142857142858, 5.936],
 [144, 14.4, 5.284722222222222],
 [44, 8.8, 5.9772727272727275],
 [75, 8.333333333333334, 5.6],
 [162, 18.0, 5.777777777777778],
 [107, 11.88888888888889, 5.5233644859813085],
 [93, 11.625, 5.67741935483871],
 [109, 9.909090909090908, 5.743119266055046],
 [111, 13.875, 5.7207207207207205],
 [78, 11.142857142857142, 5.269230769230769],
 [94, 31.333333333333332, 5.223404255319149],
 [73, 12.166666666666666, 5.301369863013699],
 [178, 14.833333333333334, 5.606741573033708],
 [81, 13.5, 5.012345679012346],
 [113, 12.555555555555555, 5.353982300884955],
 [99, 7.615384615384615, 5.848484848484849],
 [109, 13.625, 5.935779816513762],
 [143, 13.0, 5.79020979020979],
 [164, 16.4, 5.829268292682927],
 [190, 17.272727272727273, 5.557894736842106],
 [112, 12.444444444444445, 5.517857142857143],
 [148, 9.25, 5.398648648648648],
 [125, 15.625, 5.584],
 [137, 17.125, 5.875912408759124],
 [133, 26.6, 4.992481203007519],
 [125, 17.857142857142858, 6.048],
 [134, 14.88888888888889, 5.358208955223881],
 [107, 10.7, 5.392523364485982],
 [168, 14.0, 5.648809523809524],
 [57, 11.4, 6.245614035087719],
 [138, 17.25, 5.891304347826087],
 [128, 14.222222222222221, 5.2421875],
 [191, 23.875, 6.0785340314136125],
 [152, 16.88888888888889, 5.875],
 [158, 22.571428571428573, 5.3164556962025316],
 [77, 12.833333333333334, 5.701298701298701],
 [112, 11.2, 5.553571428571429],
 [31, 7.75, 5.290322580645161],
 [161, 12.384615384615385, 5.739130434782608],
 [139, 17.375, 5.697841726618705],
 [155, 14.090909090909092, 5.980645161290322],
 [60, 12.0, 5.283333333333333],
 [91, 13.0, 5.835164835164835],
 [91, 10.11111111111111, 5.395604395604396],
 [120, 10.0, 5.258333333333334],
 [106, 15.142857142857142, 5.971698113207547],
 [68, 8.5, 5.882352941176471],
 [46, 11.5, 5.891304347826087],
 [76, 12.666666666666666, 5.4605263157894735],
 [123, 13.666666666666666, 5.959349593495935],
 [141, 12.818181818181818, 5.23404255319149],
 [93, 10.333333333333334, 5.741935483870968],
 [131, 16.375, 5.816793893129771],
 [120, 20.0, 5.416666666666667],
 [127, 11.545454545454545, 5.716535433070866],
 [97, 13.857142857142858, 5.381443298969073],
 [138, 15.333333333333334, 6.101449275362318],
 [134, 8.933333333333334, 5.6940298507462686],
 [162, 16.2, 5.506172839506172],
 [133, 10.23076923076923, 5.293233082706767],
 [128, 14.222222222222221, 5.671875],
 [116, 12.88888888888889, 5.224137931034483],
 [192, 21.333333333333332, 5.604166666666667],
 [61, 12.2, 6.426229508196721],
 [140, 11.666666666666666, 5.285714285714286],
 [73, 10.428571428571429, 5.123287671232877],
 [122, 12.2, 5.622950819672131],
 [65, 9.285714285714286, 5.2153846153846155],
 [140, 11.666666666666666, 5.821428571428571],
 [139, 19.857142857142858, 5.223021582733813],
 [179, 14.916666666666666, 5.865921787709497],
 [81, 11.571428571428571, 6.049382716049383],
 [92, 10.222222222222221, 5.858695652173913],
 [120, 12.0, 5.65],
 [132, 10.153846153846153, 5.606060606060606],
 [41, 20.5, 5.365853658536586],
 [139, 15.444444444444445, 5.309352517985611],
 [180, 13.846153846153847, 5.6722222222222225],
 [167, 13.916666666666666, 5.425149700598802],
 [166, 16.6, 5.5843373493975905],
 [161, 17.88888888888889, 5.782608695652174],
 [61, 12.2, 5.737704918032787],
 [117, 14.625, 5.333333333333333],
 [183, 10.764705882352942, 5.453551912568306],
 [106, 9.636363636363637, 5.169811320754717],
 [45, 11.25, 4.688888888888889],
 [157, 14.272727272727273, 5.318471337579618],
 [127, 15.875, 5.417322834645669],
 [56, 18.666666666666668, 5.339285714285714],
 [139, 15.444444444444445, 5.575539568345324],
 [99, 14.142857142857142, 5.363636363636363],
 [94, 18.8, 5.74468085106383],
 [260, 18.571428571428573, 5.826923076923077],
 [25, 12.5, 4.88],
 [56, 11.2, 5.607142857142857],
 [141, 15.666666666666666, 5.432624113475177],
 [128, 10.666666666666666, 5.7109375],
 [109, 13.625, 5.412844036697248],
 [132, 12.0, 4.9772727272727275],
 [141, 14.1, 5.411347517730497],
 [99, 12.375, 5.545454545454546],
 [73, 12.166666666666666, 5.424657534246576],
 [126, 14.0, 5.515873015873016],
 [176, 16.0, 5.380681818181818],
 [128, 21.333333333333332, 5.703125],
 [70, 10.0, 5.3428571428571425],
 [131, 11.909090909090908, 5.541984732824427],
 [137, 13.7, 5.744525547445256],
 [147, 18.375, 5.414965986394558],
 [83, 8.3, 5.819277108433735],
 [94, 10.444444444444445, 5.670212765957447],
 [97, 12.125, 5.721649484536083],
 [124, 12.4, 5.911290322580645],
 [112, 16.0, 5.991071428571429],
 [182, 14.0, 5.5989010989010985],
 [47, 9.4, 5.787234042553192],
 [105, 9.545454545454545, 5.247619047619048],
 [104, 11.555555555555555, 5.519230769230769],
 [121, 15.125, 5.909090909090909],
 [70, 14.0, 5.628571428571429],
 [98, 16.333333333333332, 5.642857142857143],
 [134, 16.75, 5.559701492537314],
 [108, 13.5, 5.611111111111111],
 [150, 13.636363636363637, 5.786666666666667],
 [145, 11.153846153846153, 5.689655172413793],
 [109, 9.909090909090908, 5.293577981651376],
 [146, 12.166666666666666, 5.486301369863014],
 [120, 13.333333333333334, 5.616666666666666],
 [72, 12.0, 6.125],
 [82, 27.333333333333332, 5.914634146341464],
 [215, 11.944444444444445, 5.455813953488372],
 [190, 15.833333333333334, 5.568421052631579],
 [98, 9.8, 5.438775510204081],
 [58, 14.5, 5.741379310344827],
 [123, 11.181818181818182, 6.284552845528455],
 [138, 13.8, 5.681159420289855],
 [223, 20.272727272727273, 5.681614349775785],
 [131, 13.1, 5.748091603053435],
 [90, 12.857142857142858, 4.7555555555555555],
 [93, 15.5, 5.655913978494624],
 [218, 18.166666666666668, 5.490825688073395],
 [97, 10.777777777777779, 5.597938144329897],
 [144, 16.0, 5.173611111111111],
 [142, 12.909090909090908, 5.323943661971831],
 [157, 19.625, 5.6687898089171975],
 [185, 13.214285714285714, 5.594594594594595],
 [27, 13.5, 6.074074074074074],
 [179, 14.916666666666666, 5.212290502793296],
 [121, 12.1, 5.190082644628099],
 [35, 8.75, 6.0],
 [86, 10.75, 5.72093023255814],
 [89, 11.125, 5.674157303370786],
 [27, 13.5, 5.888888888888889],
 [6, 3.0, 3.5],
 [71, 11.833333333333334, 5.126760563380282],
 [193, 17.545454545454547, 5.829015544041451],
 [86, 12.285714285714286, 4.755813953488372],
 [140, 14.0, 5.5928571428571425],
 [139, 12.636363636363637, 5.381294964028777],
 [109, 13.625, 5.522935779816514],
 [106, 13.25, 5.4245283018867925],
 [49, 8.166666666666666, 5.204081632653061],
 [158, 14.363636363636363, 5.379746835443038],
 [108, 15.428571428571429, 5.768518518518518],
 [68, 11.333333333333334, 5.1911764705882355],
 [147, 13.363636363636363, 5.523809523809524],
 [141, 11.75, 5.602836879432624],
 [157, 13.083333333333334, 5.738853503184713],
 [128, 11.636363636363637, 5.8671875],
 [146, 16.22222222222222, 5.602739726027397],
 [201, 14.357142857142858, 5.616915422885572],
 [119, 17.0, 5.361344537815126],
 [132, 18.857142857142858, 5.25],
 [89, 12.714285714285714, 5.865168539325842],
 [96, 10.666666666666666, 5.84375],
 [121, 24.2, 5.355371900826446],
 [115, 16.428571428571427, 5.121739130434783],
 [83, 11.857142857142858, 5.265060240963855],
 [151, 16.77777777777778, 6.072847682119205],
 [120, 15.0, 5.516666666666667],
 [131, 14.555555555555555, 5.297709923664122],
 [93, 11.625, 5.580645161290323],
 [185, 16.818181818181817, 5.648648648648648],
 [141, 15.666666666666666, 5.397163120567376],
 [108, 10.8, 6.194444444444445],
 [132, 12.0, 5.712121212121212],
 [127, 14.11111111111111, 5.52755905511811],
 [120, 15.0, 5.608333333333333],
 [147, 10.5, 5.35374149659864],
 [160, 13.333333333333334, 5.76875],
 [68, 11.333333333333334, 5.073529411764706],
 [96, 16.0, 5.916666666666667],
 [85, 12.142857142857142, 5.5058823529411764],
 [47, 9.4, 5.680851063829787],
 [138, 13.8, 5.231884057971015],
 [117, 11.7, 5.170940170940171],
 [148, 14.8, 5.5],
 [91, 11.375, 5.3076923076923075],
 [156, 15.6, 5.653846153846154],
 [175, 13.461538461538462, 5.708571428571428],
 [110, 13.75, 5.663636363636364],
 [97, 12.125, 5.618556701030927],
 [117, 14.625, 5.427350427350428],
 [55, 7.857142857142857, 5.8],
 [182, 15.166666666666666, 6.0989010989010985],
 [168, 11.2, 5.791666666666667],
 [107, 8.916666666666666, 5.271028037383178],
 [96, 13.714285714285714, 5.447916666666667],
 [95, 11.875, 5.6947368421052635],
 [178, 12.714285714285714, 5.466292134831461],
 [171, 15.545454545454545, 5.39766081871345],
 [76, 12.666666666666666, 5.4868421052631575],
 [117, 9.75, 6.0],
 [96, 12.0, 5.739583333333333],
 [49, 9.8, 5.938775510204081],
 [116, 12.88888888888889, 6.0344827586206895],
 [102, 14.571428571428571, 5.686274509803922],
 [135, 13.5, 5.7555555555555555],
 [130, 16.25, 5.653846153846154],
 [181, 13.923076923076923, 5.668508287292818],
 [76, 12.666666666666666, 5.2631578947368425],
 [220, 16.923076923076923, 5.709090909090909],
 [41, 10.25, 5.439024390243903],
 [101, 12.625, 5.742574257425742],
 [115, 12.777777777777779, 6.034782608695652],
 [165, 11.785714285714286, 5.678787878787879],
 [105, 13.125, 5.3238095238095235],
 [101, 12.625, 5.445544554455446],
 [131, 13.1, 5.641221374045801],
 [120, 10.0, 5.108333333333333],
 [179, 11.933333333333334, 5.70391061452514],
 [62, 12.4, 6.064516129032258],
 [33, 6.6, 5.090909090909091],
 [189, 11.8125, 5.746031746031746],
 [95, 13.571428571428571, 5.663157894736842],
 [128, 16.0, 5.921875],
 [112, 12.444444444444445, 5.553571428571429],
 [144, 20.571428571428573, 5.729166666666667],
 [141, 20.142857142857142, 5.432624113475177],
 [148, 14.8, 5.378378378378378],
 [99, 14.142857142857142, 5.4646464646464645],
 [174, 12.428571428571429, 5.264367816091954],
 [149, 13.545454545454545, 5.409395973154362],
 [107, 13.375, 5.224299065420561],
 [128, 16.0, 5.390625],
 [113, 11.3, 5.716814159292035],
 [95, 9.5, 5.378947368421053],
 [126, 12.6, 5.214285714285714],
 [66, 11.0, 5.7727272727272725],
 [15, 7.5, 6.466666666666667],
 [55, 13.75, 5.636363636363637],
 [109, 10.9, 5.853211009174312],
 [89, 12.714285714285714, 5.977528089887641],
 [71, 11.833333333333334, 5.676056338028169],
 [84, 9.333333333333334, 5.488095238095238],
 [88, 14.666666666666666, 5.25],
 [82, 11.714285714285714, 5.402439024390244],
 [132, 18.857142857142858, 5.7727272727272725],
 [97, 13.857142857142858, 5.742268041237113],
 [138, 15.333333333333334, 5.340579710144928],
 [131, 13.1, 5.480916030534351],
 [120, 13.333333333333334, 5.958333333333333],
 [27, 9.0, 5.074074074074074],
 [179, 13.76923076923077, 5.787709497206704],
 [110, 12.222222222222221, 5.790909090909091],
 [89, 14.833333333333334, 5.224719101123595],
 [127, 14.11111111111111, 5.25984251968504],
 [93, 13.285714285714286, 5.827956989247312],
 [118, 9.833333333333334, 6.398305084745763],
 [105, 21.0, 5.828571428571428],
 [54, 13.5, 5.592592592592593],
 [104, 17.333333333333332, 5.375],
 [130, 13.0, 5.753846153846154],
 [185, 16.818181818181817, 5.243243243243243],
 [156, 19.5, 5.217948717948718],
 [144, 13.090909090909092, 5.513888888888889],
 [42, 10.5, 5.5],
 [14, 14.0, 6.571428571428571],
 [136, 13.6, 5.5661764705882355],
 [61, 15.25, 5.081967213114754],
 [126, 11.454545454545455, 5.857142857142857],
 [142, 10.142857142857142, 5.436619718309859],
 [88, 11.0, 5.5227272727272725],
 [124, 11.272727272727273, 5.387096774193548],
 [93, 11.625, 4.989247311827957],
 [66, 11.0, 5.363636363636363],
 [114, 14.25, 5.947368421052632],
 [247, 17.642857142857142, 5.882591093117409],
 [130, 18.571428571428573, 5.176923076923077],
 [138, 11.5, 5.405797101449275],
 [132, 11.0, 5.712121212121212],
 [145, 12.083333333333334, 4.937931034482759],
 [102, 17.0, 5.647058823529412],
 [183, 13.071428571428571, 5.437158469945355],
 [135, 12.272727272727273, 5.607407407407408],
 [271, 19.357142857142858, 5.380073800738008],
 [98, 14.0, 5.357142857142857],
 [157, 17.444444444444443, 5.656050955414012],
 [125, 13.88888888888889, 6.04],
 [96, 12.0, 5.6875],
 [124, 10.333333333333334, 5.645161290322581],
 [87, 14.5, 5.505747126436781],
 [173, 15.727272727272727, 5.491329479768786],
 [146, 16.22222222222222, 5.561643835616438],
 [172, 14.333333333333334, 5.441860465116279],
 [200, 13.333333333333334, 5.875],
 [105, 11.666666666666666, 5.495238095238095],
 [129, 12.9, 5.155038759689923],
 [158, 13.166666666666666, 5.3924050632911396],
 [169, 18.77777777777778, 5.6923076923076925],
 [144, 11.076923076923077, 5.756944444444445],
 [156, 17.333333333333332, 5.198717948717949],
 [191, 17.363636363636363, 5.450261780104712],
 [127, 11.545454545454545, 5.5984251968503935],
 [71, 14.2, 6.0],
 [155, 14.090909090909092, 5.625806451612903],
 [156, 14.181818181818182, 5.288461538461538],
 [167, 16.7, 5.74251497005988],
 [163, 16.3, 5.515337423312883],
 [86, 10.75, 5.0813953488372094],
 [126, 12.6, 5.595238095238095],
 [58, 9.666666666666666, 5.655172413793103],
 [158, 14.363636363636363, 5.291139240506329],
 [103, 12.875, 5.87378640776699],
 [53, 26.5, 4.735849056603773],
 [152, 12.666666666666666, 5.473684210526316],
 [144, 13.090909090909092, 5.701388888888889],
 [119, 19.833333333333332, 5.436974789915967],
 [113, 14.125, 5.371681415929204],
 [41, 10.25, 5.780487804878049],
 [66, 13.2, 5.636363636363637],
 [66, 11.0, 6.136363636363637],
 [115, 11.5, 5.217391304347826],
 [134, 19.142857142857142, 5.462686567164179],
 [122, 17.428571428571427, 5.172131147540983],
 [140, 12.727272727272727, 5.5],
 [142, 12.909090909090908, 5.507042253521127],
 [57, 14.25, 5.087719298245614],
 [79, 11.285714285714286, 5.924050632911392],
 [220, 14.666666666666666, 5.554545454545455],
 [76, 10.857142857142858, 5.421052631578948],
 [147, 13.363636363636363, 5.72108843537415],
 [73, 8.11111111111111, 5.8493150684931505],
 [81, 16.2, 5.827160493827161],
 [129, 12.9, 5.496124031007752],
 [129, 14.333333333333334, 5.441860465116279],
 [94, 10.444444444444445, 5.73404255319149],
 [147, 14.7, 5.816326530612245],
 [59, 9.833333333333334, 5.254237288135593],
 [106, 17.666666666666668, 5.80188679245283],
 [78, 11.142857142857142, 5.756410256410256],
 [153, 12.75, 5.555555555555555],
 [85, 17.0, 6.0588235294117645],
 [60, 12.0, 5.133333333333334],
 [71, 14.2, 5.76056338028169],
 [93, 18.6, 5.440860215053763],
 [141, 11.75, 5.716312056737588],
 [70, 11.666666666666666, 5.1571428571428575],
 [173, 17.3, 5.294797687861272],
 [161, 20.125, 5.944099378881988],
 [94, 10.444444444444445, 5.414893617021277],
 [160, 8.88888888888889, 5.8],
 [140, 12.727272727272727, 5.457142857142857],
 [122, 10.166666666666666, 5.631147540983607],
 [186, 14.307692307692308, 5.349462365591398],
 [80, 16.0, 5.1875],
 [129, 11.727272727272727, 5.635658914728682],
 [121, 12.1, 5.520661157024794],
 [110, 22.0, 5.536363636363636],
 [154, 15.4, 5.8441558441558445],
 [176, 16.0, 5.329545454545454],
 [85, 12.142857142857142, 5.752941176470588],
 [102, 12.75, 5.254901960784314],
 [103, 14.714285714285714, 5.718446601941747],
 [24, 12.0, 5.75],
 [154, 14.0, 5.616883116883117],
 [52, 17.333333333333332, 5.5576923076923075],
 [125, 13.88888888888889, 5.672],
 [182, 15.166666666666666, 5.653846153846154],
 [138, 17.25, 5.760869565217392],
 [112, 11.2, 5.508928571428571],
 [48, 8.0, 5.645833333333333],
 [153, 13.909090909090908, 5.496732026143791],
 [111, 10.090909090909092, 5.702702702702703],
 [144, 16.0, 5.548611111111111],
 [167, 15.181818181818182, 5.790419161676646],
 [143, 20.428571428571427, 5.566433566433567],
 [100, 9.090909090909092, 5.4],
 [94, 13.428571428571429, 5.659574468085107],
 [123, 12.3, 5.471544715447155],
 [52, 17.333333333333332, 5.576923076923077],
 [77, 15.4, 5.922077922077922],
 [180, 16.363636363636363, 5.8277777777777775],
 [117, 13.0, 5.111111111111111],
 [48, 9.6, 5.875],
 [154, 17.11111111111111, 5.896103896103896],
 [72, 8.0, 5.388888888888889],
 [108, 15.428571428571429, 5.611111111111111],
 [111, 22.2, 5.342342342342342],
 [97, 9.7, 5.639175257731959],
 [125, 11.363636363636363, 6.056],
 [179, 17.9, 5.4581005586592175],
 [96, 12.0, 5.677083333333333],
 [179, 13.76923076923077, 5.4860335195530725],
 [26, 13.0, 6.076923076923077],
 [48, 8.0, 6.375],
 [93, 23.25, 5.956989247311828],
 [73, 12.166666666666666, 5.328767123287672],
 [104, 14.857142857142858, 5.509615384615385],
 [158, 15.8, 5.734177215189874],
 [114, 12.666666666666666, 5.5964912280701755],
 [95, 11.875, 5.852631578947369],
 [195, 15.0, 5.153846153846154],
 [155, 14.090909090909092, 5.632258064516129],
 [58, 9.666666666666666, 5.396551724137931],
 [110, 18.333333333333332, 5.790909090909091],
 [121, 13.444444444444445, 4.950413223140496],
 [114, 11.4, 5.359649122807017],
 [151, 11.615384615384615, 5.529801324503311],
 [100, 14.285714285714286, 5.54],
 [141, 15.666666666666666, 5.76595744680851],
 [194, 16.166666666666668, 5.371134020618556],
 [95, 11.875, 5.663157894736842],
 [113, 14.125, 5.619469026548672],
 [44, 7.333333333333333, 5.136363636363637],
 [128, 12.8, 5.6640625],
 [77, 15.4, 5.6103896103896105],
 [155, 19.375, 5.819354838709677],
 [47, 9.4, 5.361702127659575],
 [98, 10.88888888888889, 6.142857142857143],
 [100, 14.285714285714286, 5.58],
 [129, 16.125, 5.24031007751938],
 [169, 15.363636363636363, 5.769230769230769],
 [71, 10.142857142857142, 5.746478873239437],
 [99, 12.375, 5.585858585858586],
 [68, 9.714285714285714, 5.279411764705882],
 [171, 17.1, 6.035087719298246],
 [142, 28.4, 5.056338028169014],
 [159, 15.9, 5.660377358490566],
 [145, 16.11111111111111, 5.544827586206897],
 [92, 11.5, 5.532608695652174],
 [140, 10.0, 5.285714285714286],
 [152, 12.666666666666666, 5.2105263157894735],
 [97, 12.125, 5.618556701030927],
 [209, 14.928571428571429, 6.100478468899522],
 [108, 10.8, 5.638888888888889],
 [153, 21.857142857142858, 5.457516339869281],
 [90, 10.0, 5.7],
 [129, 11.727272727272727, 5.666666666666667],
 [127, 14.11111111111111, 5.15748031496063],
 [93, 10.333333333333334, 5.387096774193548],
 [159, 11.357142857142858, 5.654088050314465],
 [110, 12.222222222222221, 5.890909090909091],
 [118, 10.727272727272727, 4.889830508474576],
 [251, 19.307692307692307, 5.47808764940239],
 [23, 5.75, 6.217391304347826],
 [161, 14.636363636363637, 5.559006211180124],
 [184, 15.333333333333334, 5.635869565217392],
 [142, 14.2, 5.725352112676056],
 [122, 12.2, 5.754098360655738],
 [87, 14.5, 4.942528735632184],
 [88, 14.666666666666666, 5.7727272727272725],
 [155, 11.923076923076923, 5.554838709677419],
 [160, 16.0, 5.33125],
 [107, 7.642857142857143, 5.616822429906542],
 [125, 15.625, 5.776],
 [176, 17.6, 5.3977272727272725],
 [175, 12.5, 5.257142857142857],
 [107, 17.833333333333332, 5.897196261682243],
 [138, 12.545454545454545, 5.478260869565218],
 [150, 18.75, 5.98],
 [125, 15.625, 5.568],
 [106, 13.25, 5.811320754716981],
 [150, 13.636363636363637, 5.56],
 [62, 10.333333333333334, 5.064516129032258],
 [72, 9.0, 5.472222222222222],
 [113, 11.3, 5.292035398230088],
 [123, 15.375, 6.195121951219512],
 [112, 11.2, 5.491071428571429],
 [42, 14.0, 5.714285714285714],
 [156, 19.5, 5.903846153846154],
 [128, 16.0, 5.5703125],
 [99, 14.142857142857142, 5.424242424242424],
 [123, 15.375, 5.32520325203252],

In [80]:
def essay_length(x):
  # no_of_words=0
  # no_of_sentences=0
  # total_len_of_words=0
  # no_poly_syllables=0
  # essay=x
  # #one essay
  # essay = essay.replace("!","।")
  # essay = essay.replace("?","।")
  # temp=essay.split("।")
  # # print(temp)
  # #print(temp) number of sentences
  # no_of_sentences=len(temp)
  # for j in range(len(temp)):
  #   b=temp[j].replace(","," ").split()
  #   no_of_words+=len(b)
  # return no_of_words
  return l_of_features[x][0]

In [81]:
df['essay_length'] = df["index"].apply(lambda x:essay_length(x))

In [82]:
df

,index,Unnamed: 0,essay_id,essay_set,essay,score,essay_hindi,mbart50_m2m,vocab_size,unique_words_count,overlap_score,essay_length
0,0,8886,14834,6,There were many obstacles that the builders fa...,2,एम्पायर स्टेट बिल्डिंग में डिरिगिबल्स डॉक करने...,इम्पर स्टेट भवनमा dirigibles डक गर्ने प्रयास ग...,57,50,0.001299,92
1,1,8887,14835,6,"Him from the start, there would have been many...",3,"उसे शुरू से ही, हवा में कुछ @ NUM1 फीट डॉक करन...","उहाँलाई सुरुदेखि नै, केही फीट आकाशमा डक गर्न ...",78,69,0.001432,138
2,2,8888,14836,6,The builders of the Empire State Building face...,4,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां डॉक...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,73,62,0.000842,117
3,3,8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1,मार्ग में मूरिंग मस्त मार्सिया एमिडॉन @ CAPS1 ...,मार्गमा मार्सिया अमीडन द्वारा निर्माण गरिएको ...,101,90,0.001175,157
4,4,8890,14838,6,The builders of the Empire State Building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को डिरिगिबल...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,72,60,0.001339,128
...,...,...,...,...,...,...,...,...,...,...,...,...
1795,1795,10681,16629,6,The one obstacle the builders had when trying ...,0,इस इमारत को बनाने की कोशिश करते समय बिल्डरों क...,निर्माणकर्ताहरूले यो भवन निर्माण गर्ने प्रयास ...,54,45,0.000524,113
1796,1796,10682,16630,6,Some of the problems with the constructing of ...,2,डॉकिंग डिरिगिबल्स के निर्माण के साथ कुछ समस्या...,डकिङ डाइरिभेलको निर्माणमा केही समस्याहरू निम्न...,33,32,0.000000,52
1797,1797,10683,16631,6,The builders of the Empire State building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां कुछ...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,53,44,0.000000,83
1798,1798,10684,16632,6,The obstacles the builders of the Empire State...,2,एम्पायर स्टेट बिल्डिंग के बिल्डरों की बाधाएं य...,इम्पर स्टेट भवनका निर्माणकर्ताहरूका अवरोधहरू य...,30,24,0.000000,54
1799,1799,10685,16633,6,You want me to tell you what they had to go th...,2,आप चाहते हैं कि मैं आपको बता दूं कि डिरिगिबल्स...,तपाईँले मलाई बताउन चाहनुहुन्छ तिनीहरूलाई त्यहा...,67,58,0.001352,129

In [83]:
def avg_sentence_length(x):
  return l_of_features[x][1]

In [84]:
df['average_sentence_length']=df["index"].apply(lambda x:avg_sentence_length(x))

In [85]:
def avg_word_length(x):
  return l_of_features[x][2]

In [86]:
df['average_word_length']=df["index"].apply(lambda x:avg_word_length(x))

In [87]:
def readability(x):
  return readability_score[x]

In [88]:
df['readability']=df["index"].apply(lambda x:readability(x))

In [89]:
df.head()

,index,Unnamed: 0,essay_id,essay_set,essay,score,essay_hindi,mbart50_m2m,vocab_size,unique_words_count,overlap_score,essay_length,average_sentence_length,average_word_length,readability
0,0,8886,14834,6,There were many obstacles that the builders fa...,2,एम्पायर स्टेट बिल्डिंग में डिरिगिबल्स डॉक करने...,इम्पर स्टेट भवनमा dirigibles डक गर्ने प्रयास ग...,57,50,0.001299,92,13.142857,5.934783,11.093871
1,1,8887,14835,6,"Him from the start, there would have been many...",3,"उसे शुरू से ही, हवा में कुछ @ NUM1 फीट डॉक करन...","उहाँलाई सुरुदेखि नै, केही फीट आकाशमा डक गर्न ...",78,69,0.001432,138,13.800000,5.427536,10.471367
2,2,8888,14836,6,The builders of the Empire State Building face...,4,एम्पायर स्टेट बिल्डिंग के बिल्डरों को वहां डॉक...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,73,62,0.000842,117,13.000000,5.769231,11.031525
3,3,8889,14837,6,In the passage The Mooring Mast by Marcia Amid...,1,मार्ग में मूरिंग मस्त मार्सिया एमिडॉन @ CAPS1 ...,मार्गमा मार्सिया अमीडन द्वारा निर्माण गरिएको ...,101,90,0.001175,157,15.700000,5.484076,10.771646
4,4,8890,14838,6,The builders of the Empire State Building face...,3,एम्पायर स्टेट बिल्डिंग के बिल्डरों को डिरिगिबल...,इम्पर स्टेट भवनका निर्माणकर्ताहरूले जहाजलाई त्...,72,60,0.001339,128,11.636364,5.656250,10.950543

In [90]:
df.to_csv('/content/drive/MyDrive/EG/translated_dataset/mbart50/mbart50_p6_fe.csv', index=False)